### ISSUE TITLE
vue-ssr-renderer-demo/vuecli2ssr/的打包后 run dev APP.vue->style内的样式没有编译进入

### ISSUE THREAD

**Issue by ZTrainWilliams** [heiyu4585/vue-ssr-renderer-demo#1]
run devHot 一切正常；
run dev  文字未居中，点击事件无效

**Comment by heiyu4585** [comment]
我测试下正常
你访问 http://localhost:8003/pageList/1 呢
会报错什么的吗 ,有什么包没安装全吗

**Comment by heiyu4585** [comment]
抱歉,造成一点误解

以修改为 npm run simpleStart  这个只是一个简单的实现,没有弄开发环境

 1. run dev APP.vue->style内的样式没有编译进入
修复 
npm run simpleStart 
2.run dev 文字未居中，点击事件无效 这个未复现
